;;; rhombus-theme.el --- A black theme for Emacs 24

;; Copyright (C) 2015 Ross Donaldson

;; Author: Ross Donaldson <gastove@gmail.com>
;; URL: https://github.com/Gastove/rhombus-theme
;; Version 1.0.0

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;;; Credits:

;; This theme inspired by (and based heavily on) badger-theme.el by Cody
;; Canning, and flatland-back-theme, (which was auto-generated by, as best as I
;; can tell, Jason Milkins). The structure of this theme was based on
;; zenburn-theme.el by Bozhidar Batsov

;;; Code:
(deftheme rhombus "The Rhombus color theme")

;; Rhombus Color Palette
(defvar rhombus-colors-alit
  '(("rhombus-fg"             . "#F8F8F8")
    ("rhombus-fg+1"           . "#FBF9F3")
    ("rhombus-bg"             . "#000000")
    ("rhombus-bg+1"           . "#171717")

;; The Main Pallette
    ("rhombus-red             . "#9e1200"")
    ("rhombus-orange"         . "#D84c00")
    ("rhombus-yellow"         . "#9c9a00")
    ("rhombus-green"          . "#24992c")
    ("rhombus-blue")
    ("rhomus-violet")

;; Backup-dancing colors
    ()

;; Other People's Good Ideas
    ("rhombus-link")
    ("rhombus-warn")
    ("rhombus-succ")
    ("rhombus-hl")
    ))

;;; rhombus-theme.el ends here
